### ISSUE TITLE
Support to Linux Mint 19.1

### ISSUE THREAD

**Issue by DaniloNC** [docker/docker-install#134]
Although the Linux Mint 19.1 is based on Ubuntu 18.04, the docker-install script recognize this distribution as a debian buster/sid.

This was working until recently but started to give me some problems when using vscode, see comment https://github.com/microsoft/vscode-remote-release/issues/1041#issuecomment-516596330

The `https://get.docker.com | sh`, when running from a Linux Mint 19.1 should add the ubuntu bionic repo instead of debian buster.

**Comment by ptandler** [comment]
Same applies to linux mint 20, it should be treated as ubuntu focal

**Comment by ptandler** [comment]
I changed the install script to also check /etc/os-release for ID_LIKE (= "ubuntu") and UBUNTU_CODENAME (for mint 20 it's "focal"). This works fine for me in Linux Mint 20 Ulyana
See https://github.com/ptandler/docker-install/tree/issue134-mint-support

**Comment by ptandler** [comment]
I just created a pull request https://github.com/docker/docker-install/pull/185

**Comment by thaJeztah** [comment]
Yes, we don't provide packages for that Linux distro; as mentioned above, it's _possible_ that packages for other similar distros work, but we don't want to update the script to automatically "guess" something that "could" work, because no testing/verification is done on those distros, and we try to avoid "pretending" that it's supported / tested. Also see https://docs.docker.com/engine/install/#other-linux-distros

My general recommendation would be to;

- Verify if the packages work for your situation / distro (in a testing environment)
- If they do, and you're comfortable running them on your systems, and if you need to automate setups; create a script based on the steps of this script;
    - you can use `--dry-run` to see the steps it executes
    - or (as the script largely automates the manual installation steps); base your script on the instructions for the distro you're installing packages for; e.g. https://docs.docker.com/engine/install/centos/

_Maybe_ (to be discussed) we could consider a manual "I know what I'm doing" option that allows overriding these options (e.g. as suggested in https://github.com/docker/docker-install/pull/229, or a `--override-distro=xxx` flag), but that needs to be discussed.

I'm closing this ticket for now, but feel free to continue the conversation or to open a ticket with a proposal for alternatives.
