### ISSUE TITLE
ERROR: Unsupported distribution ' '

### ISSUE THREAD

**Issue by Behnaz64** [docker/docker-install#165]
Hello everyone

I'm trying to install docker on my MacOS with the Docker Installation Scripts provided here, i.e.

curl -fsSL https://get.docker.com -o get-docker.sh
sh get-docker.sh
AND
curl -fsSL https://test.docker.com -o test-docker.sh
sh test-docker.sh

But both commands return the same error message:

Executing docker install script, commit:442e66405c304fa92af8aadaa1d9b31bf4b0ad94
ERROR: Unsupported distribution ' '

Could you tell me what's wrong here?

Thank you

**Comment by StefanScherer** [comment]
@Behnaz64 The get.docker.com script only works for Linux. We have updated the script to give you a link to download Docker Desktop for Mac.

**Comment by 1221li** [comment]
Dear Engineer
I had the same problem with Linux
sh get-docker.sh
# Executing docker install script, commit: 3d8fe77c2c46c5b7571f94b42793905e5b3e42e4

ERROR: Unsupported distribution ''
I want to know whether this is caused by not adding "sudo", or other reasons, and how to solve this problem.
I sincerely look forward to your reply!

**Comment by Thunermay** [comment]
why is this closed? I'm trying to install it on a synology NAS with an ARMv7 chip. So I really need this to install a pi-hole!!

**Comment by thaJeztah** [comment]
We don't have packages for Synology, so the script is not detecting that as a Linux distro for which it can install docker.

You may be able to manually install packages that are intended for other distros, or download the static binaries, but no guarantees if that works (definitely untested)
