### ISSUE TITLE
Broken on the latest Ubuntu 20.04 LTS (Focal Fossa)

### ISSUE THREAD

**Issue by inadarei** [docker/docker-install#169]
Installation script errors-out on the latest Ubuntu with the error message:

```
E: The repository 'https://download.docker.com/linux/ubuntu focal Release' does not have a Release file.
```

**Comment by Sirtea** [comment]
I'm interested on getting this fixed. I've been waiting for Ubuntu lts for so long and now it's useless as a docker server... Shame

**Comment by nemchik** [comment]
https://download.docker.com/linux/ubuntu/dists/ does not contain a folder for 20.04 (`focal`) meaning `docker-ce` has not yet been released in any capacity for 20.04 (`focal`). This has nothing to do with the install script in this repo. The install script merely uses the repo linked above to install the correct version released for your distro. Note that 18.04 (`bionic`) (here: https://download.docker.com/linux/ubuntu/dists/bionic/pool/ ) has the following release channels:

- `edge`
- `nightly`
- `stable`
- `test`

20.04 (`focal`) will get these when they are ready.

Separately you may note that https://github.com/docker/docker-ce-packaging does seem to include mentions of 20.04 (`focal`) however there has not been a release for the tool in that repo since March https://github.com/docker/docker-ce-packaging/releases I am not positive that a release in this repo would result in builds happening for `docker-ce` to be released for 20.04 (`focal`), but just by looking around the repos it seems like a decent guess.

**Comment by Sirtea** [comment]
That's true. When this happened with debian 10, the script had a "case" preventing to reach this step. The script for Ubuntu just places the keyword "fossal" and would work if the repository existed

**Comment by inadarei** [comment]
@Sirtea "useless as a docker server" is a bit of an exaggeration. I was able to install Docker on Ubuntu 20.x using the release from Ubuntu 18.x, but what is broken is this easy installation script.

**Comment by StefanScherer** [comment]
Thank you. We are already working on this internally. The next patch release is expected to have packages for Ubuntu Focal Fossa.

**Comment by nicktags** [comment]
apt install docker.io will work until the repo is fixed.

**Comment by m-alborov** [comment]
> apt install docker.io will work until the repo is fixed.

Looks like the repo is fixed, there is the "focal" folder

[https://download.docker.com/linux/ubuntu/dists/focal/](https://download.docker.com/linux/ubuntu/dists/focal/)

**Comment by nicktags** [comment]
Folder is there but the script is still broke.

E: Package 'docker-ce' has no installation candidate

**Comment by StefanScherer** [comment]
@m-alborov yes, containerd came in on Friday. This week we'll publish docker-ce 19.03.9

**Comment by nicktags** [comment]
@StefanScherer  thank you, please keep us posted.

**Comment by StefanScherer** [comment]
Docker 19.03.9 is released, with packages for Ubuntu Focal Fossa.
Thanks for you patience. Enjoy!
