### ISSUE TITLE
I cant install on linux mint 20

### ISSUE THREAD

**Issue by lucasmanica** [docker/docker-install#187]
I cant install this, the scripts is broken!!.
``` 
lucas@lucas-Inspiron-5567:~$ curl -fsSL https://raw.githubusercontent.com/docker/docker-install/master/install.sh | sh
# Executing docker install script, commit: 
+ sudo -E sh -c apt-get update -qq >/dev/null
E: The repository 'https://download.docker.com/linux/debian bullseye Release' does not have a Release file.
lucas@lucas-Inspiron-5567:~$ cat /etc/debian_version
bullseye/sid
lucas@lucas-Inspiron-5567:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 20
Release:	20
Codename:	ulyana
```

**Comment by ibtehajali67** [comment]
In Case of Docker installation ,just run these commands step by step written bellow;

1. `sudo apt-get -y install apt-transport-https ca-certificates curl software-properties-common`
2. `curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - 2>/dev/null`
3. `echo -e "\ndeb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable" | sudo tee -a /etc/apt/sources.list`
4. `sudo apt-get -y update`
5. `sudo apt-get -y install docker-ce docker-ce-cli containerd.io`

**Comment by thaJeztah** [comment]
Yes, we don't provide packages for that Linux distro; as mentioned above, it's _possible_ that packages for other similar distros work, but we don't want to update the script to automatically "guess" something that "could" work, because no testing/verification is done on those distros, and we try to avoid "pretending" that it's supported / tested. Also see https://docs.docker.com/engine/install/#other-linux-distros

My general recommendation would be to;

- Verify if the packages work for your situation / distro (in a testing environment)
- If they do, and you're comfortable running them on your systems, and if you need to automate setups; create a script based on the steps of this script;
    - you can use `--dry-run` to see the steps it executes
    - or (as the script largely automates the manual installation steps); base your script on the instructions for the distro you're installing packages for; e.g. https://docs.docker.com/engine/install/centos/

_Maybe_ (to be discussed) we could consider a manual "I know what I'm doing" option that allows overriding these options (e.g. as suggested in https://github.com/docker/docker-install/pull/229, or a `--override-distro=xxx` flag), but that needs to be discussed.

I'm closing this ticket for now, but feel free to continue the conversation or to open a ticket with a proposal for alternatives.
