### ISSUE TITLE
docker install failing on Ubuntu 14.04 with docker-ce-rootless-extras package not found

### ISSUE THREAD

**Issue by parepallykiran** [docker/docker-install#222]
Running below command on Ubuntu 14.04 is failing with mentioned error:

Command:
curl -sSL https://get.docker.com/ | sh

Error:
sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq docker-ce-rootless-extras >/dev/null
E: Unable to locate package docker-ce-rootless-extras

We don't see required package is available for Ubuntu v14.04. Its available only from Ubuntu 20.x. https://download.docker.com/linux/ubuntu/dists/trusty/pool/stable/amd64/

We are using Vagrant docker provisioner and vagrant is running above mentioned command to install docker on VM. This worked without any issues in the past.

**Comment by joeried** [comment]
I could observe the same problem here with Debian 9 (stretch)

**Comment by AkihiroSuda** [comment]
Ubuntu 14.04 and Debian 9 reached EOL, so they are no longer supported

**Comment by yuezhu** [comment]
Could it skip the installation for `docker-ce-rootless-extras` on Ubuntu 14.04?

**Comment by thaJeztah** [comment]
The convenience script at get.docker.com is to install the latest version of docker; given that 14.04 and debian 9 reached EOL, and we no longe update those packages, we won't update the script for things we no longer ship.

 I _highly_ recommend upgrading your systems as they're no longer receiving updates (including security fixes); and older version of docker contain unpatched vulnerabilities (some of which may be _critical_).

If you really need to install on older platforms for some reason; either

- copy the install script and update it for your situation
- download an older version of the script from github (probably the commit before https://github.com/docker/docker-install/pull/215)
- follow the manual installation procedure from https://docs.docker.com/engine/install/ubuntu/ or https://docs.docker.com/engine/install/debian/

I'm closing this ticket because of the above, but feel free to continue the conversation
