### ISSUE TITLE
https://test.docker.com/ is out of sync with this repo

### ISSUE THREAD

**Issue by ramereth** [docker/docker-install#265]
Similar to what was reported in #219, the script used on the test URL is out of sync with this repo since 26ff363bcf3b3f5a00498ac43694bf1c7d9ce16c. Can you please update it? We're having issues using the script with Debian 11 (bullseye).

**Comment by thaJeztah** [comment]
The script has been re-deployed a couple of times since, and is now at 6d9743e9656cc56f699a64800b098d5ea5a60020

We'll probably do a new deploy next week, as the scripts are a bit behind current; https://github.com/docker/docker-install/compare/6d9743e9656cc56f699a64800b098d5ea5a60020...dd4d114074ecd649c37aa17e688c55fbd4c032fb
