### ISSUE TITLE
Cannot install on linux mint 21

### ISSUE THREAD

**Issue by gjm19761** [docker/docker-install#321]
lsb_release -a
No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 21
Release:	21
Codename:	vanessa

download.docker.com tries to give us 

E: The repository 'https://download.docker.com/linux/debian bookworm Release' does not have a Release file.

any way to tweak the get.docker.com install script to detect linux 21 vanessa as ubuntu jammy ??? im using dockstarter and it goes to get,docker.com to try and get docker release but of course it adds the wrong repositary for mint 21

**Comment by dirtyhandscm** [comment]
ever find a solution to this?

**Comment by thaJeztah** [comment]
Yes, we don't provide packages for that Linux distro; as mentioned above, it's _possible_ that packages for other similar distros work, but we don't want to update the script to automatically "guess" something that "could" work, because no testing/verification is done on those distros, and we try to avoid "pretending" that it's supported / tested. Also see https://docs.docker.com/engine/install/#other-linux-distros

My general recommendation would be to;

- Verify if the packages work for your situation / distro (in a testing environment)
- If they do, and you're comfortable running them on your systems, and if you need to automate setups; create a script based on the steps of this script;
    - you can use `--dry-run` to see the steps it executes
    - or (as the script largely automates the manual installation steps); base your script on the instructions for the distro you're installing packages for; e.g. https://docs.docker.com/engine/install/centos/

_Maybe_ (to be discussed) we could consider a manual "I know what I'm doing" option that allows overriding these options (e.g. as suggested in https://github.com/docker/docker-install/pull/229, or a `--override-distro=xxx` flag), but that needs to be discussed.

I'm closing this ticket for now, but feel free to continue the conversation or to open a ticket with a proposal for alternatives.
