### ISSUE TITLE
elementary os 7 horus has no release file

### ISSUE THREAD

**Issue by rshpeley** [docker/docker-install#341]
On elementary os 7 horus (built on Ubuntu 22.04.2 LTS) I get the error,

```bash
E: The repository 'https://download.docker.com/linux/ubuntu horus Release' does not have a Release file.
````
When will this file be released?

There's a similar issue with nodejs, but it was a [simple script change to get it to install](https://github.com/nodesource/distributions/issues/1513).

I followed the [Docker Docs instructions](https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository) to install, so it seems this isn't the right place to post. Can someone suggest where I can post this issue?

**Comment by Thalhammer** [comment]
Same issue but slightly different solution, so I'll post it here again.
You need to replace all occurrences in the docker apt file with jammy.
To do so open a terminal and enter this:
```bash
sudo sed -i 's/horus/jammy/g' /etc/apt/sources.list.d/docker.list
```
Enter your password and after that do `apt update` to update the package lists.
Now `apt install docker` should work fine.

**Comment by tropicdev** [comment]
Can confirm that this worked. Thank you 

> Same issue but slightly different solution, so I'll post it here again. You need to replace all occurrences in the docker apt file with jammy. To do so open a terminal and enter this:
> 
> ```shell
> sudo sed -i 's/horus/jammy/g' /etc/apt/sources.list.d/docker.list
> ```
> 
> Enter your password and after that do `apt update` to update the package lists. Now `apt install docker` should work fine.

**Comment by IgorBVieira** [comment]
Thanks man, worked fine

> Same issue but slightly different solution, so I'll post it here again. You need to replace all occurrences in the docker apt file with jammy. To do so open a terminal and enter this:
> 
> ```shell
> sudo sed -i 's/horus/jammy/g' /etc/apt/sources.list.d/docker.list
> ```
> 
> Enter your password and after that do `apt update` to update the package lists. Now `apt install docker` should work fine.

**Comment by terceranexus6** [comment]
This worked for me as well, but I have to write:

```
sudo sed -i 's/horus/jammy/g' /etc/apt/sources.list.d/openmeteo-api.list 
```

Thank you guys!

**Comment by jrichardsz** [comment]
It works!! Thanks

> Same issue but slightly different solution, so I'll post it here again. You need to replace all occurrences in the docker apt file with jammy. To do so open a terminal and enter this:
> 
> ```shell
> sudo sed -i 's/horus/jammy/g' /etc/apt/sources.list.d/docker.list
> ```
> 
> Enter your password and after that do `apt update` to update the package lists. Now `apt install docker` should work fine.

It works!! Thanks

**Comment by thaJeztah** [comment]
Yes, we don't provide packages for that Linux distro; as mentioned above, it's _possible_ that packages for other similar distros work, but we don't want to update the script to automatically "guess" something that "could" work, because no testing/verification is done on those distros, and we try to avoid "pretending" that it's supported / tested. Also see https://docs.docker.com/engine/install/#other-linux-distros

My general recommendation would be to;

- Verify if the packages work for your situation / distro (in a testing environment)
- If they do, and you're comfortable running them on your systems, and if you need to automate setups; create a script based on the steps of this script;
    - you can use `--dry-run` to see the steps it executes
    - or (as the script largely automates the manual installation steps); base your script on the instructions for the distro you're installing packages for; e.g. https://docs.docker.com/engine/install/centos/

_Maybe_ (to be discussed) we could consider a manual "I know what I'm doing" option that allows overriding these options (e.g. as suggested in https://github.com/docker/docker-install/pull/229, or a `--override-distro=xxx` flag), but that needs to be discussed.

I'm closing this ticket for now, but feel free to continue the conversation or to open a ticket with a proposal for alternatives.
