### ISSUE TITLE
Need solution for running dev container with rootless Docker

### ISSUE THREAD

**Issue by jcr010910** [docker/docker-install#432]
Writing to the host filesystem fails unless the container is run with root privileges.

Steps to Reproduce:
1. Set up rootless Docker environment (dockerd-rootless-setuptool.sh install)
2. Start a development container (docker run ...)
3. Attempt to write files from the container to the host filesystem (echo "test" > /host/path/file.txt)

Expected Behavior:
Files should be written successfully to the host filesystem without needing to run the container as root.

**Comment by thaJeztah** [comment]
Closing, as off-topic for this issue tracker, and because this  GitHub issue tracker is not intended as a general support, consider using one of;

- the [Discussione](https://github.com/moby/moby/discussions) on the Moby repository
- the [Docker community Slack channel](https://dockr.ly/comm-slack)
- the `docker` tags on [StackOverflow](https://stackoverflow.com/questions/tagged/docker*)
- the Docker Support Forums - https://forums.docker.com

I'm closing this ticket because of the above, but feel free to continue the conversation 👍
