### ISSUE TITLE
x86_64-amzn-2017.09 support

### ISSUE THREAD

**Issue by kraney** [docker/docker-install#45]
Amazon Linux is a fedora variant. It would be nice if it was supported natively. Current VERSION_ID is 2017.09, although I imagine older versions are easily supported as well.

**Comment by seemethere** [comment]
ping @friism

**Comment by friism** [comment]
I'm afraid Docker doesn't support Amazon Linux. We currently recommend using a Docker-supported Linux distro on AWS, eg. Fedora, Ubuntu, CentOS or similar.

**Comment by kraney** [comment]
Really? It's a complete surprise to me as I've been using Docker on Amazon Linux for some time, simply by running 'yum -y install docker' which currently gets you version 17.06.2ce.

**Comment by seemethere** [comment]
@kraney We don't officially support Docker for Amazon Linux (hence it not being in the install script) but that does not mean that Docker will not run on a particular distribution.

The version of Docker that you are receiving by running `yum -y install docker` is not official and YMMV but it could run fine.

If you are particularly set on using Amazon Linux I would suggest following the installation instructions found on our website for centOS installation. Otherwise I'd recommend using an officially supported distribution like centOS or Fedora.

**Comment by seemethere** [comment]
Closing this for now

**Comment by friism** [comment]
@kraney to expand on @seemethere's message, note that Docker CE 17.06.X is no longer maintained by Docker and is note receiving security or bugfix updates. To stay up to date, install Docker on a supported operating system. The last stable version is 17.09.
